### ISSUE TITLE
AttributeError: Accessing private attribute '_on_timestep_end' is prohibited.

### ISSUE THREAD

**Issue by AminMoradiXL** [FilippoAiraldi/mpc-reinforcement-learning#2]
When I try to run q_learning.py

**Comment by FilippoAiraldi** [comment]
Thanks for spotting the problem!

Most likely, the issue is due to the fact that the example code you are trying to run is from a relatively recent commit, but the `mpcrl` pip package has been released quite some time ago, i.e.,  `mpcrl==1.1.0`.

I solved the issue altogether by releasing the new version 1.1.1, which was due anyway. Now, the example code you can find on this repo should be in line with the pip package.
